// Komputile generataj mallongigo-listoj
// Ne ŝanĝu mane. Vidu 'MallongigoListoj.swift' en ReVoDatumbazo.

final class MallongigoListo {
	/// Tekstaj mallongigoj uzataj en artikoloj
	static let vortaraj = [
		("*", "fundamenta"),
		("1", "1a oficiala aldono"),
		("2", "2a oficiala aldono"),
		("3", "3a oficiala aldono"),
		("4", "4a oficiala aldono"),
		("5", "5a oficiala aldono"),
		("6", "6a oficiala aldono"),
		("7", "7a oficiala aldono"),
		("8", "8a oficiala aldono"),
		("9", "9a oficiala aldono"),
		("a.K.", "antaŭ Kristo"),
		("abs.", "absolute, senkomplemente"),
		("adj.", "adjektivo"),
		("adv.", "adverbo"),
		("akuz.", "akuzativo"),
		("anst.", "anstataŭ"),
		("ark.", "arkaismo"),
		("B", "Bein"),
		("C", "Christaller"),
		("ĉap.", "ĉapitro"),
		("D", "Millidge"),
		("E-o", "Esperanto"),
		("ekz.", "ekzemple"),
		("F", "Fulcher k Long"),
		("f", "figure, metafore"),
		("fam.", "familio"),
		("G", "Grabowski"),
		("G.", "genro"),
		("i.a.", "interalia"),
		("inf.", "infinitivo"),
		("interj.", "interjekcio"),
		("jc", "jarcento"),
		("K", "Krestomatio"),
		("k. a.", "kaj aliaj"),
		("kc", "kaj ceteraj"),
		("konj.", "konjunkcio"),
		("Kp", "Komparu"),
		("ks", "kaj similaj"),
		("ktp", "kaj tiel plu"),
		("LI", "Lingvo Internacia"),
		("LK", "Lingva Komitato"),
		("N", "Bennemann"),
		("ntr", "netransitiva"),
		("p.", "paĝo(j)"),
		("part.", "participo"),
		("pp", "parolante pri"),
		("pref.", "prefikso"),
		("prep.", "prepozicio"),
		("pron.", "pronomo"),
		("prop.", "propozicio"),
		("R", "Rollet de l'Isle"),
		("resp.", "respektive"),
		("Rim.", "Rimarko"),
		("simb.", "simbolo"),
		("sk", "subkomprenu"),
		("subst.", "substantivo"),
		("suf.", "sufikso"),
		("t.e.", "tio estas"),
		("tr", "transitiva"),
		("trad.", "tradukis"),
		("Vd", "Vidu"),
		("veg.", "vegetaĵo"),
		("vol.", "volumo"),
		("x", "transitiva kaj netransitiva"),
		("Y", "diversaj aliaj vortaristoj"),
		("Z", "Zamenhof"),
	]

	/// Mallongaj faknomoj, uzataj anstataŭ bildetoj en ĉi-apo
	static let fakaj = [
		("AGR", "agrokulturo"),
		("ARKE", "arkeologio"),
		("ARKI", "arkitekturo"),
		("AST", "astronomio"),
		("AŬT", "aŭtomobiloj"),
		("AVI", "aviado"),
		("BAK", "bakteriologio, virusologio"),
		("BELA", "belartoj"),
		("BELE", "beletro"),
		("BIB", "biblio"),
		("BIO", "biologio, biontologio"),
		("BOT", "botaniko"),
		("BUD", "budhismo"),
		("EKOL", "ekologio"),
		("EKON", "ekonomiko, financo, komerco"),
		("ELE", "elektro"),
		("ELET", "elektrotekniko"),
		("ESP", "esperantismo"),
		("FER", "fervojoj"),
		("FIL", "filozofio"),
		("FIZ", "fiziko"),
		("FIZL", "fiziologio"),
		("FON", "fonetiko"),
		("FOT", "fotografio, optiko"),
		("GEN", "genealogio"),
		("GEOD", "geodezio, topografio"),
		("GEOG", "geografio"),
		("GEOL", "geologio"),
		("GRA", "gramatiko"),
		("HER", "heraldiko"),
		("HIN", "hinduismo"),
		("HIS", "historio"),
		("ANA", "homa anatomio, histologio"),
		("HOR", "hortikulturo, arbokulturo, silvikulturo"),
		("ISL", "islamo"),
		("JUR", "juro"),
		("KAL", "kalendaro, tempomezurado"),
		("KAT", "katolikismo"),
		("KEM", "kemio, biokemio"),
		("KIN", "kinoarto"),
		("KIR", "kirurgio"),
		("KOMP", "komputiko"),
		("KON", "konstrutekniko"),
		("KRI", "kristanismo"),
		("KUI", "kuirarto"),
		("LIN", "lingvistiko, filologio"),
		("MAR", "maraferoj"),
		("MAŜ", "maŝinoj, mekaniko"),
		("MAT", "matematiko"),
		("MED", "medicino, farmacio"),
		("MET", "meteologio"),
		("MIL", "militaferoj"),
		("MIN", "mineralogio"),
		("MIT", "mitologio"),
		("MUZ", "muziko"),
		("NOM", "nomoj"),
		("PAL", "paleontologio"),
		("PED", "pedagogio"),
		("PERS", "personoj"),
		("POE", "poetiko, poezio"),
		("POL", "politiko, sociologio, administrado"),
		("POŜ", "poŝto"),
		("PRA", "prahistorio"),
		("TIP", "presarto, libroj"),
		("PSI", "psikologio, psikiatrio"),
		("RAD", "radiofonio"),
		("REL", "religioj"),
		("RET", "retoj, Interreto"),
		("SCI", "sciencoj"),
		("SPO", "sporto, ludoj"),
		("ŜIP", "ŝipkonstruado, navigado"),
		("TEA", "teatro"),
		("TEK", "teknikoj"),
		("TEKS", "teksindustrio, vestoj"),
		("TEL", "telekomunikoj"),
		("TRA", "trafiko"),
		("ZOO", "zoologio"),
	]
}
