// Komputile generataj mallongigo-listoj
// Ne ŝanĝu mane. Vidu 'MallongigoListoj.swift' en ReVoDatumbazo.

enum MallongigoListo {
	/// Tekstaj mallongigoj uzataj en artikoloj
	static let vortaraj: [(String, String)] = [
		("*", "fundamenta"),
		("1", "1a oficiala aldono"),
		("2", "2a oficiala aldono"),
		("3", "3a oficiala aldono"),
		("4", "4a oficiala aldono"),
		("5", "5a oficiala aldono"),
		("6", "6a oficiala aldono"),
		("7", "7a oficiala aldono"),
		("8", "8a oficiala aldono"),
		("9", "9a oficiala aldono"),
		("a.K.", "antaŭ Kristo"),
		("abs.", "absolute, senkomplemente"),
		("adj.", "adjektivo"),
		("adv.", "adverbo"),
		("akuz.", "akuzativo"),
		("anst.", "anstataŭ"),
		("ark.", "arkaismo"),
		("B", "Bein"),
		("C", "Christaller"),
		("ĉap.", "ĉapitro"),
		("D", "Millidge"),
		("E-o", "Esperanto"),
		("ekz.", "ekzemple"),
		("F", "Fulcher k Long"),
		("f", "figure, metafore"),
		("fam.", "familio"),
		("G", "Grabowski"),
		("G.", "genro"),
		("i.a.", "interalia"),
		("inf.", "infinitivo"),
		("interj.", "interjekcio"),
		("jc", "jarcento"),
		("K", "Krestomatio"),
		("k. a.", "kaj aliaj"),
		("kc", "kaj ceteraj"),
		("konj.", "konjunkcio"),
		("Kp", "Komparu"),
		("ks", "kaj similaj"),
		("ktp", "kaj tiel plu"),
		("LI", "Lingvo Internacia"),
		("LK", "Lingva Komitato"),
		("N", "Bennemann"),
		("ntr", "netransitiva"),
		("p.", "paĝo(j)"),
		("part.", "participo"),
		("pp", "parolante pri"),
		("pref.", "prefikso"),
		("prep.", "prepozicio"),
		("pron.", "pronomo"),
		("prop.", "propozicio"),
		("R", "Rollet de l'Isle"),
		("resp.", "respektive"),
		("Rim.", "Rimarko"),
		("simb.", "simbolo"),
		("sk", "subkomprenu"),
		("subst.", "substantivo"),
		("suf.", "sufikso"),
		("t.e.", "tio estas"),
		("tr", "transitiva"),
		("trad.", "tradukis"),
		("Vd", "Vidu"),
		("veg.", "vegetaĵo"),
		("vol.", "volumo"),
		("x", "transitiva kaj netransitiva"),
		("Y", "diversaj aliaj vortaristoj"),
		("Z", "Zamenhof"),
	]

	/// Mallongaj faknomoj, uzataj anstataŭ bildetoj en ĉi-apo
	static let fakaj: [(String, String)] = [
		("AGR", "agrokulturo"),
		("ARKE", "arkeologio"),
		("ARKI", "arkitekturo"),
		("AST", "astronomio"),
		("AŬT", "aŭtomobiloj"),
		("AVI", "aviado"),
		("BAK", "bakteriologio, virusologio"),
		("BELA", "belartoj"),
		("BELE", "beletro"),
		("BIB", "biblio"),
		("BIO", "biologio, biontologio"),
		("BOT", "botaniko"),
		("BUD", "budhismo"),
		("EKOL", "ekologio"),
		("EKON", "ekonomiko, financo, komerco"),
		("ELE", "elektro"),
		("ELET", "elektrotekniko"),
		("ESP", "esperantismo"),
		("FER", "fervojoj"),
		("FIL", "filozofio"),
		("FIZ", "fiziko"),
		("FIZL", "fiziologio"),
		("FON", "fonetiko"),
		("FOT", "fotografio, optiko"),
		("GEN", "genealogio"),
		("GEOD", "geodezio, topografio"),
		("GEOG", "geografio"),
		("GEOL", "geologio"),
		("GRA", "gramatiko"),
		("HER", "heraldiko"),
		("HIN", "hinduismo"),
		("HIS", "historio"),
		("ANA", "homa anatomio, histologio"),
		("HOR", "hortikulturo, arbokulturo, silvikulturo"),
		("ISL", "islamo"),
		("JUR", "juro"),
		("KAL", "kalendaro, tempomezurado"),
		("KAT", "katolikismo"),
		("KEM", "kemio, biokemio"),
		("KIN", "kinoarto"),
		("KIR", "kirurgio"),
		("KOMP", "komputiko"),
		("KON", "konstrutekniko"),
		("KRI", "kristanismo"),
		("KUI", "kuirarto"),
		("LIN", "lingvistiko, filologio"),
		("MAR", "maraferoj"),
		("MAŜ", "maŝinoj, mekaniko"),
		("MAT", "matematiko"),
		("MED", "medicino, farmacio"),
		("MET", "meteologio"),
		("MIL", "militaferoj"),
		("MIN", "mineralogio"),
		("MIT", "mitologio"),
		("MUZ", "muziko"),
		("NOM", "nomoj"),
		("PAL", "paleontologio"),
		("PED", "pedagogio"),
		("PERS", "personoj"),
		("POE", "poetiko, poezio"),
		("POL", "politiko, sociologio, administrado"),
		("POŜ", "poŝto"),
		("PRA", "prahistorio"),
		("TIP", "presarto, libroj"),
		("PSI", "psikologio, psikiatrio"),
		("RAD", "radiofonio"),
		("REL", "religioj"),
		("RET", "retoj, Interreto"),
		("SCI", "sciencoj"),
		("SPO", "sporto, ludoj"),
		("ŜIP", "ŝipkonstruado, navigado"),
		("TEA", "teatro"),
		("TEK", "teknikoj"),
		("TEKS", "teksindustrio, vestoj"),
		("TEL", "telekomunikoj"),
		("TRA", "trafiko"),
		("ZOO", "zoologio"),
	]

	/// Mallongaj nomoj de la verkoj de la vortara bibliografio
	static let bibliografiaj: [(String, String)] = [
		("ADL", "Dro Esperanto (L. L. Zamenhof)\n<k>Aldono al la “Dua Libro de l’ Lingvo Internacia”</k>\n1888"),
		("Aventuroj", "Privat Edmond\n<k>Aventuroj de pioniro</k>\n1963"),
		("AzS", "Victor Sadler\n<k>Azia Strategio</k>\n1963"),
		("BEE", "Montague J. Butler\n<k>Esperanto-English Dictionary</k>\n1967"),
		("BT", "Douglas A. Portmann\n<k>Biblioteka terminaro</k>"),
		("BazRad", "Wouter F. Pilger\n<k>Bazaj Radikoj Esperanto-Esperanto</k>"),
		("BdV", "Charles Dickens\ntrd. L. L. Zamenhof\n<k>La Batalo de l' Vivo</k>\n1891"),
		("Bird", "Mészáros Béla\n<k>Oklingva nomaro de eŭropaj birdoj</k>\n1980"),
		("BoE", "Werner Bormann\n<k>Entrepreno. Entreprenistaj Strategioj: Priskribo de la entrepreno</k>\n1991"),
		("BoER", "E. Bokarev\n<k>Esperanta-rusa vortaro</k>\n1974"),
		("BoM", "Werner Bormann\n<k>Mondkomerco kaj Lingvo</k>\n1993"),
		("BoRE", "E. Bokarev\n<k>Rusa-esperanta vortaro</k>\n1966"),
		("BoT", "Werner Bormann\n<k>La Merkato de Trafikservoj</k>\n1992"),
		("BonaLingvo", "Claude Piron\n<k>La bona lingvo</k>\n1989"),
		("BonaS-ino", "E. Orzeszko\ntrd. Kazimierz Bein\n<k>La bona sinjorino</k>"),
		("CCT", "The Esperanto Institute Limited\n<k>Common Commercial Terms in English and Esperanto</k>\n1926"),
		("CDE", "Paul Gottfried Christaller\n<k>Deutsch-Esperanto Wörterbuch</k>\n1910"),
		("CEE", "Peter J. Benson\n<k>Comprehensive English-Esperanto Dictionary</k>\n1995"),
		("CKv", "Johán Valano\n<k>Ĉu ni kunvenis vane?</k>\n1982"),
		("CRI", "<k>Ĉina Radio Internacia enrete</k>"),
		("ChB", "Johán Valano\n<k>Ĉu li bremsis sufiĉe?</k>\n1979"),
		("ChC", "Johán Valano\n<k>Ĉu vi kuiras ĉine?</k>\n1996"),
		("ChL", "Henri Vallienne\n<k>Ĉu li?</k>\n2003"),
		("ChM", "Johán Balano\n<k>Ĉu ŝi mortu tra-fike?</k>\n2000"),
		("ChP", "Petro Chrdle\n<k>Profesia uzo de Esperanto kaj ĝiaj specifaj trajtoj</k>\n1995"),
		("ChR", "Johán Valano\n<k>Ĉu rakonti novele?</k>\n1986"),
		("ChV", "Johán Valano\n<k>Ĉu li venis trakosme?</k>\n1980"),
		("DKM", "Don Miguel de Cervantes Saavedra\n<k>Don Kiĥoto de la Manĉo en Barcelono (5 ĉapitroj)</k>\n1909"),
		("DKo", "Sten Johansson\n<k>Denaska kongresano</k>\n1992"),
		("DL", "L. L. Zamenhof\n<k>Dua Libro de l’ lingvo Internacia</k>\n1888"),
		("DOz", "L. Frank Baum\ntrd. D. Broadribb\n<k>Doroteo kaj la Sorĉisto en Oz</k>\n1996"),
		("DanĝLng", "Ulrich Lins\n<k>La danĝera lingvo, studo pri la persekutoj kontraŭ Esperanto</k>\n1990"),
		("DdH", "L. L. Zamenhof\n<k>Aldono al la „Dogmoj de Hilelismo“</k>\n1906"),
		("Deneva", "Daniela Deneva\n<k>Esperanta-Bulgara-Rusa Matematika Terminaro</k>\n1985"),
		("DonKihxoto", "Miguel de Cervantes Saavedra\ntrd. Fernando de Diego\n<k>La inĝenia hidalgo Don Quijote de la Mancha</k>\n1977"),
		("EBV", "Rüdiger Eichholz\n<k>Esperanta Bildvortaro</k>\n1989"),
		("EE", "L. L. Zamenhof\n<k>Esenco kaj Estonteco</k>"),
		("EFM", "Ruysschaert\n<k>Economie, finance, monnaie. Glosaro de la komisiono de la Eŭropaj Komunumoj. Versio esperanto ― français ― english </k>\n1992"),
		("EHW", "Paul Bennemann\n<k>Esperanto Hand-Wörterbuch</k>\n1923-1926"),
		("EKV", "k.a.\n<k>EK-Vortaro de matematikaj terminoj</k>\n1980"),
		("ELNAN", "Diversaj aŭtoroj\n<k>ELNA Newsletter</k>\n1952-1996"),
		("EPĈ", "El Popola Ĉinio\n<k>El Popola Ĉinio (revuo)</k>\nde 1950"),
		("EdE", "<k>Enciklopedio de Esperanto</k>\n1979"),
		("EeP", "Ivo Lapenna, Tazio Carlevaro kaj Ulrich Lins\n<k>Esperanto en Perspektivo</k>\n1974"),
		("Eek", "Esperanto-Rondo\n<k>Esperanto en Komerco. Esperanto in Commerce</k>\n1964"),
		("EfI", "Ivo Lapenna\n<k>Por pli efika informado</k>\n1974"),
		("ElektFab", "Wilhelm Grimm\ntrd. Kazimierz Bein\n<k>Elektitaj Fabeloj de Fratoj Grimm</k>\n2002"),
		("EncCxi", "Zhang Meizhi\ntrd. Fan Yizhu, Xu Senrong\n<k>Enciklopedieto de Ĉinio</k>\n1994"),
		("EncJap", "T. Nakamura\n<k>Enciklopedieto japana</k>\n1964"),
		("Esperanto", "Universala Esperanto-Asocio\n<k>Esperanto</k>\n1905-"),
		("F", "L. L. Zamenhof\n<k>Fundamento de Esperanto</k>\n1905"),
		("FIL", "Frankfurter Messamt\n<k> Pri la solvo de l'problemo de internacia lingvo por komerco kaj trafiko. </k>\n1923"),
		("FK", "Ludoviko Lazaro Zamenhof\n<k>Fundamenta Krestomatio de la lingvo Esperanto</k>\n1904"),
		("FSI", "Ulrich Matthias\n<k>Fajron sentas mi interne</k>\n1990"),
		("FSp", "Edmond Privat\n<k>Federala Sperto</k>\n1958"),
		("FT", "EFE - Terminara Komisiono\n<k>Fervoja Terminaro</k>\n1997"),
		("Fab1", "H. C. Andersen\ntrd. L. L. Zamenhof\n<k>Fabeloj, vol. 1</k>\n1926"),
		("Fab2", "H. C. Andersen\ntrd. L. L. Zamenhof\n<k>Fabeloj, vol. 2</k>\n1926"),
		("Fab3", "H. C. Andersen\ntrd. L. L. Zamenhof\n<k>Fabeloj, vol. 3</k>\n1932"),
		("Fab4", "H. C. Andersen\ntrd. L. L. Zamenhof\n<k>Fabeloj, vol. 4</k>\n1963"),
		("Far1", "B. Prus\ntrd. Kazimierz Bein\n<k>La Faraono, vol. 1</k>\n1927"),
		("Far2", "B. Prus\ntrd. Kazimierz Bein\n<k>La Faraono, vol. 2</k>\n1926"),
		("Far3", "B. Prus\ntrd. Kazimierz Bein\n<k>La Faraono, vol. 3</k>\n1926"),
		("FdO", "Władyław Reymont\ntrd. Kazimierz Bein\n<k>En fumejo de l'opio</k>\n1908"),
		("FzT", "Makino J. (komp.)\n<k>Esperanta terminaro de fiziko, Esperanto ― japana ― angla. Reviziita </k>\n1992"),
		("GDEF", "Gaston Waringhien\n<k>Grand dictionnaire espéranto-français</k>\n1957"),
		("GDEFS", "Gaston Waringhien\n<k>Grand dictionnaire espéranto-français avec Supplément</k>\n1976"),
		("GDFE", "k.a.\n<k>Grand dictionnaire français espéranto</k>\n1992"),
		("GDn", "Molière\ntrd. D-ro L. L. Zamenhof\n<k>Georgo Dandin</k>\n1908"),
		("GLI", "L. L. Zamenhof\n<k>Gentoj kaj Lingvo Internacia</k>\n1912"),
		("GVER", "Boris Kondratjev\n<k>Granda Vortaro Esperanto-Rusa kaj Rusa-Esperanta</k>"),
		("Gerda", "Claude Piron\n<k>Gerda malaperis</k>"),
		("GhR", "Sten Johansson\n<k>Ĝis revido, krokodilido!</k>\n1996"),
		("Gmn", "Ŝalom Alejĥem\n<k>La Gimnazio</k>\n1929"),
		("Gv", "Claus Günkel (Nikolao)\n<k>La Gunkela vortaro de vortoj mankantaj en PIV 2002</k>\n2002"),
		("HMS", "Sten Johansson\n<k>Hitler, Maŭ, Strindberg kaj mi</k>\n1996"),
		("Hamlet", "William Shakespeare\ntrd. L. L. Zamenhof\n<k>Hamleto, Reĝido de Danujo</k>\n1894"),
		("HejmVort", "k.a.\n<k>Hejma Vortaro</k>\n1999"),
		("Homaranismo", "L. L. Zamenhof\n<k>Homaranismo</k>\n1906"),
		("HomojManĝantaj", "Hemmi Yô\ntrd. Doi ĉieko\n<k>Homoj manĝantaj</k>\n2002"),
		("HsT", "Stellan Engholm\n<k>Homoj sur la tero</k>\n2001"),
		("IK", "Eliza Orzeszko\ntrd. Kazimierz Bein\n<k>La Interrompita Kanto</k>\n1928"),
		("IKEV", "F. Munniksma (eld.)\n<k>Internacia komerca-ekonomika vortaro en 11 lingvoj</k>\n1990"),
		("IKr", "Inko\n<k>Internacia krestomatio</k>\n2002"),
		("IdO", "Hendrik J. Bulthuis\n<k>Idoj de Orfeo</k>\n1923"),
		("Ifigenio", "J. W. Goethe\ntrd. L. L. Zamenhof\n<k>Ifigenio en Taŭrido</k>\n1908"),
		("InfanTorent2", "Stellan Engholm\n<k>Infanoj en Torento, dua libro en la Torento-trilogio</k>\n2001"),
		("IntArkeol", "Marinko Givoje\n<k>Interesa arkeologio</k>\n1973"),
		("IntKui", "Maria Becker-Meisberger\n<k>Internacie kuiri</k>\n2000"),
		("ItEsp", "Carlo Minnaja\n<k>Vocabolario Italiano-Esperanto</k>\n1996"),
		("Iŝtar", "H. A. Luyken\n<k>Pro Iŝtar</k>\n1924"),
		("JDE", "Hermann Jürgensen, M. Pagnier, red. L.L. Zamenhof\n<k>Wörterbuch Deutsch-Esperanto</k>\n1906"),
		("JED", "Hermann Jürgensen, red. L.L. Zamenhof\n<k>Wörterbuch Esperanto-Deutsch</k>\n1905"),
		("JEN", "Diversaj aŭtoroj\n<k>JEN</k>\n1962-1986"),
		("JV", "Ŝilo, G.\n<k>Jura Vortaro esperante-ruse-ukraine-angla</k>\n1994"),
		("Jamburg", "Mikaelo Bronŝtejn\n<k>Oni ne pafas en Jamburg</k>\n1993"),
		("JuanReg", "k.a.\n<k>Serta gratulatoria in honorem Juan Régulo</k>\n1987"),
		("KFl", "Julij Muraŝkovskij\n<k>Kien fluas roj’ Castalie</k>"),
		("KKl", "John Merchant\n<k>Kompatinda Klem</k>\n1931"),
		("KKr", "Ferenc Szilágyi\n<k>Koko Krias Jam!</k>\n1955"),
		("KPr", "Henri Vallienne\n<k>Kastelo de Prelongo</k>\n2002"),
		("KVS", "Robert Kreuz\n<k>Komerca Vortaro Seslingva. Germana ― Angla ― Franca ― Itala ― Hispana ― Esperanta </k>\n1927"),
		("KZG", "L. L. Zamenhof\n<k>Kion Zamenhof ne povis diri en Ĝenevo</k>\n1959"),
		("Kalendaro", "Cherpillod André\n<k>La kalendaro tra la tempo, tra la spaco</k>\n2002"),
		("Kandid", "Volter\ntrd. Eugen Lanti\n<k>Kandid aŭ la optimismo</k>\n1929"),
		("KelS", "<k>Kajeroj el la Sudo</k>"),
		("KielAkvo", "Raymond Schwartz\n<k>Kiel akvo de l' rivero</k>\n1991"),
		("Kiso", "Hjalmar Söderberg\ntrd. Sten Johansson\n<k>La Kiso kaj dek tri aliaj noveloj</k>\n1995"),
		("KompLeks", "Sergio Pokrovskij\n<k>Komputada Leksikono</k>"),
		("Komputeko", "<k>Komputeko</k>"),
		("Kon11", "Diversaj aŭtoroj\n<k>Kontakto 2011-2019</k>\n2011-2019"),
		("Kosmo", "Amri Wandel\n<k>La kosmo kaj ni ― Galaksioj, planedoj kaj vivo en la universo</k>\n2001"),
		("KrB", "Louis Beaucaire\n<k>Kruko kaj Baniko el Bervalo</k>\n1974"),
		("KrDE", "Erich Dieter Krause\n<k>Wörterbuch Deutsch-Esperanto</k>\n1993"),
		("KrED", "Erich Dieter Krause\n<k>Großes Wörterbuch Esperanto-Deutsch</k>\n1999"),
		("KrED2", "Erich Dieter Krause\n<k>Vollständiges Wörterbuch Esperanto-Deutsch</k>\n2018"),
		("KrM", "Cezaro Rossetti\n<k>Kredu min, sinjorino!</k>\n1950"),
		("Kukobak", "k.a.\n<k>Kukobakado</k>\n1993"),
		("LAE", "John Christopher Wells\n<k>Lingvistikaj aspektoj de Esperanto</k>\n1978"),
		("LBe", "L. L. Zamenhof\n<k>Nefermita letero al s-ro de Beaufront</k>\n1929"),
		("LF", "Kooperativo de LF\n<k>Literatura Foiro</k>"),
		("LGA", "Ferenc Szilágyi\n<k>La Granda Aventuro</k>\n1945"),
		("LOdE", "Sezonoj\n<k>La Ondo de Esperanto</k>"),
		("LR", "L. L. Zamenhof\n<k>Lingvaj Respondoj</k>"),
		("LSB", "Raymond Schwartz\n<k>La Stranga Butiko</k>\n1931"),
		("LSF", "Kalocsay\n<k>Lingvo, Stilo, Formo</k>\n1931"),
		("LSV", "E. Lanti\n<k>„Liberiga Stelo“ al la Verdruĝuloj</k>"),
		("LaFamilio", "Bakin (Li Yaotang)\ntrd. Wei Yida\n<k>La Familio</k>\n1999"),
		("LanLin", "Bertilo Wennergren\n<k>Landoj kaj lingvoj de la mondo</k>"),
		("Lanti", "E. Lanti\n<k>Vortoj de k-do Lanti</k>\n1931"),
		("Lasta", "Władysław Reymont\ntrd. Kazimierz Bein\n<k>La Lasta</k>\n1965"),
		("Lasu", "Claude Piron\n<k>Lasu min paroli plu!</k>"),
		("Lkn", "Hermano Bermano\n<k>Leksara kolekto de ofte uzataj propraj nomoj</k>\n1989"),
		("LtE", "Henrik Seppik\n<k>La tuta Esperanto</k>\n1987"),
		("Lusin", "Lusin (Zhou Shuren)\ntrd. S. J. Zee k.a.\n<k>Noveloj de Lusin</k>\n1963"),
		("MB", "ESF\n<k>Malbabelo</k>\n1994-"),
		("MD02", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2002-2004</k>\n2002-2004"),
		("MD05", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2005-2007</k>\n2005-2007"),
		("MD08", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2008-2010</k>\n2008-2010"),
		("MD11", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2011-2013</k>\n2011-2013"),
		("MD14", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2014-2016</k>\n2014-2016"),
		("MD17", "Diversaj aŭtoroj\n<k>Le Monde diplomatique en Esperanto 2017-2019</k>\n2017-2019"),
		("MEE", "Edward Alfred Millidge\n<k>The Esperanto-English dictionary</k>\n1912"),
		("MEV", "Eugen Wüster\n<k>Maŝinfaka Esperanto-vortaro</k>\n1923"),
		("MJA", "Anna Löwenstein\n<k>La memoraĵoj de Julia Agripina</k>\n2021"),
		("MMa", "Jorge Camacho\n<k>La Majstro kaj Martinelli</k>\n1993"),
		("MPe", "Kálman Kalocsay\n<k>Mia penso</k>\n1957"),
		("MT", "Brita kaj Alilanda Biblia Societo\ntrd. L. L. Zamenhof\n<k>La Malnova Testamento</k>"),
		("Malben", "Mary Webb\ntrd. Grace Kirkwood\n<k>Malbeno Kara</k>\n2000"),
		("ManPol", "k. a.\n<k>Deklingva manlibro pri politiko</k>\n1994"),
		("Marta", "Eliza Orzeszkowa\ntrd. L. L. Zamenhof\n<k>Marta</k>\n1924"),
		("Mary", "M. Lermontov\ntrd. N. Danovskij\n<k>Princidino Mary</k>\n1996"),
		("MatStokTerm", "Olav Reiersøl\n<k>Matematika kaj Stokastika Terminaro Esperanta</k>\n1994"),
		("MatTerm", "Raoul Bricard\n<k>Matematika Terminaro kaj Krestomatio</k>\n1905"),
		("MatVort", "Jan Werner\n<k>Matematika Vortaro, Esperanta-Ĉeĥa-Germana</k>\n1990"),
		("MemLapenna", "Birthe Lapenna\n<k>Memore al Ivo Lapenna</k>\n1998"),
		("Metrop", "V. Varankin\n<k>Metropoliteno</k>"),
		("MkM", "Mihail Bulgakov\ntrd. Sergio Pokrovskij\n<k>La majstro kaj Margarita</k>\n1991"),
		("Monato", "Flandra Esperanto-Ligo\n<k>Monato</k>\nde 1980"),
		("MortulŜip", "B. Traven\ntrd. Hans Georg Kaiser\n<k>Mortula Ŝipo, Rakonto de usona maristo</k>\n2001"),
		("MrA", "H. A. Luyken\n<k>Mirinda Amo</k>\n1913"),
		("Munchhausen", "R. E. Raspe\ntrd. J. D. Applebaum\n<k>[La Vojaĝoj kaj] Mirigaj Aventuroj de Barono Münchhausen</k>\n1927"),
		("MuzTerm", "D. G. Hill ind.\n<k>Muzika terminaro</k>\n1992"),
		("NT", "Brita kaj Alilanda Biblia Societo\n<k>La Nova Testamento</k>"),
		("NePiv", "A. Cherpillod\n<k>Nepivaj vortoj</k>\n1988"),
		("NeoGlo", "H. Vatré\n<k>Neologisma glosaro, postrikolto al PIV</k>\n1989"),
		("NeĝaBlovado", "Aleksandr Puŝkin\ntrd. Antoni Grabowski\n<k>La neĝa blovado</k>\n1993"),
		("OA10", "Akademio de Esperanto\n<k>Deka Oficiala Aldono al la Universala Vortaro</k>\n2023"),
		("OA9", "Akademio de Esperanto\n<k>Naŭa Oficiala Aldono al la Universala Vortaro</k>\n2007"),
		("OIP", "Spomenka Štimec\n<k>Ombro sur interna pejzaĝo</k>\n1984-"),
		("OV", "L. L. Zamenhof\n<k>Originala Verkaro</k>\n1929"),
		("Oomoto", "Oomoto\n<k>Oomoto</k>\n1925-"),
		("OriginoDeSpecioj", "Ĉarlz Darvin\ntrd. Klivo Lendon\n<k>La Origino de Specioj</k>"),
		("PAG", "Waringhien Gaston\n<k>Plena Analiza Gramatiko de Esperanto</k>\n1985"),
		("PGM", "L. L. Zamenhof\n<k>Post la granda milito</k>\n1922"),
		("PGl", "Bernard\n<k>Parnasa Gvidlibro</k>\n1984"),
		("PIV1", "SAT\n<k>Plena Ilustrita Vortaro</k>\n1970"),
		("PIV2", "SAT\n<k>La Nova Plena Ilustrita Vortaro</k>\n2002"),
		("PIV3", "SAT\n<k>Plena Ilustrita Vortaro de Esperanto 2005</k>\n2005"),
		("PMEG", "Bertilo Wennergren\n<k>Plena Manlibro de Esperanta Gramatiko</k>"),
		("PV", "E. Grosjean-Maupin\n<k>Plena Vortaro de Esperanto</k>\n1934"),
		("PVEF", "Emile Boirac\n<k>Plena Vortaro Esperanto-Esperanta kaj Esperanto-Franca</k>\n1909"),
		("Paroloj", "L. L. Zamenhof\n<k>Paroloj</k>"),
		("PatrojFiloj", "I. S. Turgenjev\ntrd. Kazimierz Bein\n<k>Patroj kaj filoj</k>\n[proks. 1938]"),
		("Plumamikoj", "Marjorie Boulton\n<k>Ne nur leteroj de plum-amikoj</k>\n1984"),
		("PoŝAtlas", "Bohumil Stehlík (red.)\n<k>Poŝatlaso de la mondo</k>\n1971"),
		("PrV", "C. Rogister ed.\n<k>Proverbaro esperanta</k>\n1974"),
		("QuV", "Henryk Sienkiewicz\ntrd. Lidia Zamenhof\n<k>Quo Vadis</k>\n1957"),
		("RBa", "Henri Heine\n<k>La Rabeno de Baĥaraĥ</k>\n1929"),
		("RLN", "Akademio de Esperanto\n<k>Listo de Rekomendataj Landnomoj</k>\n2009"),
		("RabistFab", "Josef Čapek\n<k>La unua rabista fabelo</k>"),
		("Rabistoj", "Frederiko Schiller\ntrd. L. L. Zamenhof\n<k>La rabistoj</k>\n1928"),
		("RdE", "Dro Zamenhof\n<k>Pri Reformoj en Esperanto</k>\n1907"),
		("Ret", "Ivo Lapenna\n<k>Retoriko</k>\n1971"),
		("Revadoj", "Jean-Jacques Rousseau\ntrd. André Gilles\n<k>La revadoj de soleca promenanto</k>"),
		("Revizoro", "N. V. Gogol\ntrd. L. L. Zamenhof\n<k>La Revizoro</k>"),
		("Rob", "Daniel Defo\ntrd. Pastro A. Krafft\n<k>Robinsono Kruso</k>\n1908"),
		("RokPop", "B. Wennergren\n<k>Roko kaj Popo, Popularmuzika Terminaro en Esperanto</k>"),
		("Rsp", "Platono\n<k>La Respubliko (πολιτεια)</k>\n2000"),
		("RugxDom", "Cao Xueqin\ntrd. Xie Yuming\n<k>Ruĝdoma sonĝo</k>\n1995"),
		("SPIV", "SAT\n<k>Plena Ilustrita Vortaro de Esperanto, Suplemento</k>\n1987"),
		("SPV", "Gaston Waringhien\n<k>Plena Vortaro de Esperanto, Suplemento</k>\n1953"),
		("Salamandroj", "Karel Čapek\ntrd. J. Vondroušek\n<k>Milito kontraŭ salamandroj</k>"),
		("SatirRak", "Sándor Szathmári\n<k>Satiraj rakontoj</k>\n1957-1972"),
		("ScTerm", "Maurice Rollet de l'Isle\n<k>Scienca Fundamenta Esperanta Terminaro</k>\n1931"),
		("Sezonoj", "Sezonoj\n<k>almanako Sezonoj</k>\n1984-1990"),
		("SkandalJozef", "Valdemar Vinař\n<k>La skandalo pro Jozefo</k>\n2002"),
		("Sol", "H. P. Lovecraft\n<k>La Soleno</k>"),
		("SrT", "Adam Mickiewicz\ntrd. Antoni Grabowski\n<k>Sinjoro Tadeo</k>\n1918"),
		("StU", "Anna Löwenstein\n<k>La ŝtona urbo</k>\n2000"),
		("Studoj", "Vilmos Benczik\n<k>Studoj pri la Esperanta Literaturo</k>\n1980"),
		("TAA", "John Merchant\n<k>Tri Angloj Alilande</k>\n1936"),
		("TK", "\n<k>Ilustrita terminaro de kombinita transporto, franca, angla, germana, esperanta, serba</k>\n1998"),
		("TW", "Rudolf Haferkorn\n<k>Technisches Wörterbuch Deutsch-Esperanto</k>\n1967"),
		("TermKurs", "Jan Werner\n<k>Terminologia Kurso</k>\n1986"),
		("TkI", "Prof. D-ro Hideo Yagi\n<k>Tokio invitas vin</k>\n1963"),
		("Tor", "Stellan Engholm\n<k>Al Torento</k>\n2001"),
		("UL", "Esperanto (L. L. Zamenhof)\n<k>Unua Libro</k>\n1887"),
		("UV", "L. L. Zamenhof\n<k>Universala Vortaro</k>\n1894"),
		("UrdHadda", "Deck Dorval\n<k>Urd Hadda murdita!</k>\n1990"),
		("V", "Charles Verax\n<k>Enciklopedia vortareto Esperanta</k>\n1910"),
		("VRA", "Inko\ntrd. Ferenc Szilágyi\n<k>Vespera ruĝo anoncas ventegon</k>\n2001"),
		("VaK", "Sándor Szathmári\n<k>Vojaĝo al Kazohinio</k>\n1998"),
		("VdE", "Kazimierz Bein\n<k>Vortaro de Esperanto</k>\n1912"),
		("Vetero", "Lewis Spolton\n<k>Vetero kaj klimato de la mondo</k>\n1987"),
		("ViV", "Stellan Engholm\n<k>Vivo vokas</k>\n2001"),
		("Viki", "<k>Vikipedio</k>\nde 2001"),
		("VivZam", "Edmond Privat\n<k>Vivo de Zamenhof</k>\n1937"),
		("VojaĝImp", "Valdemar Langlet\n<k>Vojaĝimpresoj</k>\n2003"),
		("Vojaĝo", "Boris Kolker\n<k>Vojaĝo en Esperanto-lando</k>\n2002"),
		("WAPS", "William Auld\n<k>Pajleroj kaj stoploj</k>\n1997"),
		("WED", "J.C. Wells\n<k>Esperanto Dictionary Esperanto-English, English-Esperanto</k>\n1969"),
		("ZR", "Eugen Wüster\n<k>Zamenhof-radikaro</k>\n1927"),
		("ZVER", "L. L. Zamenhof\n<k>Vortaro Esperanto-Rusa</k>\n1909"),
		("Zam", "Ernest Drezen\n<k>Zamenhof</k>\n2000"),
		("ondo-de-esperanto", "Diversaj aŭtoroj\n<k>La Ondo de Esperanto</k>\n2001 – 2004"),
		("ĈA", "Ĉina Esperanto-Eldonejo\n<k>Ĉina Antologio (1919-1949)</k>\n1986"),
		("Ĉukĉoj", "Vasilij Eroŝenko\n<k>El vivo de ĉukĉoj</k>\n1933"),
		("ĉuSn", "E. Lanti\n<k>Ĉu ili estas sennaciistoj?</k>"),
		("Ŝtalrato", "Harry Harrison\ntrd. Reinhard Fössmeier k.a.\n<k>Naskiĝo de la rustimuna ŝtalrato</k>\n1996"),
	]
}
